# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.0
jobs:
  build:
    branches:
      ignore:
        - master 
    docker:
      # specify the version you desire here
      - image: circleci/clojure:boot-2.7.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      BOOT_JVM_OPTIONS: "-Xms512m -Xmx1024m"

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1b:53:b2:3b:13:e1:bc:cf:5f:a7:96:61:fd:d0:3d:4b"
      - run: 
          command: |
            git config --global user.email ${email}
            git config --global user.name ${userName} 
      - run: 
          command: if [ "${CIRCLE_BRANCH}" == "blog" ]; then ./build.sh; else echo "Skipped"; fi

